steps:
  # 1. Build Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-laravel', '.']

  # 2. Push Image ke Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-laravel']

  # 3. Jalankan Migrasi (Menggunakan image yang baru dibuild)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker run --rm \
        -e DB_CONNECTION=mysql \
        -e DB_SOCKET=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME} \
        -e DB_DATABASE=${_DB_DATABASE} \
        -e DB_USERNAME=${_DB_USERNAME} \
        -e DB_PASSWORD=${_DB_PASSWORD} \
        gcr.io/$PROJECT_ID/app-laravel \
        php artisan migrate --force

# Gunakan substitusi variabel agar aman
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: "project:region:instance"
  _DB_DATABASE: "lms_pasundan"
  _DB_USERNAME: "root_app"
  _DB_PASSWORD: "liG6oe}[-m(70abM"